name: Generate profile summary cards

on:
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: main
          UTC_OFFSET: 8
          EXCLUDE: VHDL
          AUTO_PUSH: true
